name: Update README Stats Brownyroll

on:
  push:
    branches: [ main ]

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Packages
        run: npm install axios dayjs

      - name: Update README
        run: node .github/scripts/update-readme.js
        env:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
