
name: Update README Stats
permissions:
  contents: write

on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch: 
  push:
    branches: [ main ]

jobs:
  update-readme:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'2
        cache-dependency-path: '.github/scripts/package.json'
    
    - name: Install dependencies
      run: |
        cd .github/scripts
        npm install
    
    - name: Update README
      run: |
        cd .github/scripts
        node update-readme.js
      env:
        GITHUB_TOKEN: ${{ secrets.G_TOKEN }}
    
    - name: Log update
      run: |
        echo "$(date): README updated" >> .github/logs/readme.md
        name: Update README Stats Brownyroll
